/**
 * @author Balamurugan Tamilmani
 *
 */
 
CREATE TABLE PERSON 
   (	PERSON_ID NUMBER primary key, 
	FIRST_NAME VARCHAR2(20), 
	LAST_NAME VARCHAR2(20), 
	AGE NUMBER(3,0), 
	SALARY NUMBER(10,2)
   );

 CREATE TABLE PERSON_TRAIL 
   (	PERSON_ID NUMBER, 
	FIRST_NAME VARCHAR2(20), 
	LAST_NAME VARCHAR2(20), 
	AGE NUMBER(3,0), 
	SALARY NUMBER(10,2), 
	REVISION NUMBER(10,0), 
	ACTION VARCHAR2(10), 
	 FOREIGN KEY (REVISION)
	  REFERENCES REVINFO (REV) ENABLE
   );
   
 CREATE TABLE REVINFO 
   (	REV NUMBER(10,0) NOT NULL ENABLE, 
	REVTSTMP NUMBER(19,0), 
	 PRIMARY KEY (REV));
	 
	 
